<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ["name" => "Afghanistan", "slug" => "afghanistan", "calling_code" => "93", "iso_code_two_digit" => "AF", "iso_code_three_digit" => "AFG"],
            ["name" => "Aland Islands", "slug" => "aland-islands", "calling_code" => "358", "iso_code_two_digit" => "AX", "iso_code_three_digit" => "ALA"],
            ["name" => "Albania", "slug" => "albania", "calling_code" => "355", "iso_code_two_digit" => "AL", "iso_code_three_digit" => "ALB"],
            ["name" => "Algeria", "slug" => "algeria", "calling_code" => "213", "iso_code_two_digit" => "DZ", "iso_code_three_digit" => "DZA"],
            ["name" => "American Samoa", "slug" => "american-samoa", "calling_code" => "1684", "iso_code_two_digit" => "AS", "iso_code_three_digit" => "ASM"],
            ["name" => "Andorra", "slug" => "andorra", "calling_code" => "376", "iso_code_two_digit" => "AD", "iso_code_three_digit" => "AND"],
            ["name" => "Angola", "slug" => "angola", "calling_code" => "244", "iso_code_two_digit" => "AO", "iso_code_three_digit" => "AGO"],
            ["name" => "Anguilla", "slug" => "anguilla", "calling_code" => "1264", "iso_code_two_digit" => "AI", "iso_code_three_digit" => "AIA"],
            ["name" => "Antarctica", "slug" => "antarctica", "calling_code" => "672", "iso_code_two_digit" => "AQ", "iso_code_three_digit" => "ATA"],
            ["name" => "Antigua and Barbuda", "slug" => "antigua-and-barbuda", "calling_code" => "1268", "iso_code_two_digit" => "AG", "iso_code_three_digit" => "ATG"],
            ["name" => "Argentina", "slug" => "argentina", "calling_code" => "54", "iso_code_two_digit" => "AR", "iso_code_three_digit" => "ARG"],
            ["name" => "Armenia", "slug" => "armenia", "calling_code" => "374", "iso_code_two_digit" => "AM", "iso_code_three_digit" => "ARM"],
            ["name" => "Aruba", "slug" => "aruba", "calling_code" => "297", "iso_code_two_digit" => "AW", "iso_code_three_digit" => "ABW"],
            ["name" => "Australia", "slug" => "australia", "calling_code" => "61", "iso_code_two_digit" => "AU", "iso_code_three_digit" => "AUS"],
            ["name" => "Austria", "slug" => "austria", "calling_code" => "43", "iso_code_two_digit" => "AT", "iso_code_three_digit" => "AUT"],
            ["name" => "Azerbaijan", "slug" => "azerbaijan", "calling_code" => "994", "iso_code_two_digit" => "AZ", "iso_code_three_digit" => "AZE"],
            ["name" => "Bahamas", "slug" => "bahamas", "calling_code" => "1242", "iso_code_two_digit" => "BS", "iso_code_three_digit" => "BHS"],
            ["name" => "Bahrain", "slug" => "bahrain", "calling_code" => "973", "iso_code_two_digit" => "BH", "iso_code_three_digit" => "BHR"],
            ["name" => "Bangladesh", "slug" => "bangladesh", "calling_code" => "880", "iso_code_two_digit" => "BD", "iso_code_three_digit" => "BGD"],
            ["name" => "Barbados", "slug" => "barbados", "calling_code" => "1246", "iso_code_two_digit" => "BB", "iso_code_three_digit" => "BRB"],
            ["name" => "Belarus", "slug" => "belarus", "calling_code" => "375", "iso_code_two_digit" => "BY", "iso_code_three_digit" => "BLR"],
            ["name" => "Belgium", "slug" => "belgium", "calling_code" => "32", "iso_code_two_digit" => "BE", "iso_code_three_digit" => "BEL"],
            ["name" => "Belize", "slug" => "belize", "calling_code" => "501", "iso_code_two_digit" => "BZ", "iso_code_three_digit" => "BLZ"],
            ["name" => "Benin", "slug" => "benin", "calling_code" => "229", "iso_code_two_digit" => "BJ", "iso_code_three_digit" => "BEN"],
            ["name" => "Bermuda", "slug" => "bermuda", "calling_code" => "1441", "iso_code_two_digit" => "BM", "iso_code_three_digit" => "BMU"],
            ["name" => "Bhutan", "slug" => "bhutan", "calling_code" => "975", "iso_code_two_digit" => "BT", "iso_code_three_digit" => "BTN"],
            ["name" => "Bolivia", "slug" => "bolivia", "calling_code" => "591", "iso_code_two_digit" => "BO", "iso_code_three_digit" => "BOL"],
            ["name" => "Bonaire, Sint Eustatius and Saba", "slug" => "bonaire-sint-eustatius-and-saba", "calling_code" => "599", "iso_code_two_digit" => "BQ", "iso_code_three_digit" => "BES"],
            ["name" => "Bosnia and Herzegovina", "slug" => "bosnia-and-herzegovina", "calling_code" => "387", "iso_code_two_digit" => "BA", "iso_code_three_digit" => "BIH"],
            ["name" => "Botswana", "slug" => "botswana", "calling_code" => "267", "iso_code_two_digit" => "BW", "iso_code_three_digit" => "BWA"],
            ["name" => "Bouvet Island", "slug" => "bouvet-island", "calling_code" => "55", "iso_code_two_digit" => "BV", "iso_code_three_digit" => "BVT"],
            ["name" => "Brazil", "slug" => "brazil", "calling_code" => "55", "iso_code_two_digit" => "BR", "iso_code_three_digit" => "BRA"],
            ["name" => "British Indian Ocean Territory", "slug" => "british-indian-ocean-territory", "calling_code" => "246", "iso_code_two_digit" => "IO", "iso_code_three_digit" => "IOT"],
            ["name" => "Brunei Darussalam", "slug" => "brunei-darussalam", "calling_code" => "673", "iso_code_two_digit" => "BN", "iso_code_three_digit" => "BRN"],
            ["name" => "Bulgaria", "slug" => "bulgaria", "calling_code" => "359", "iso_code_two_digit" => "BG", "iso_code_three_digit" => "BGR"],
            ["name" => "Burkina Faso", "slug" => "burkina-faso", "calling_code" => "226", "iso_code_two_digit" => "BF", "iso_code_three_digit" => "BFA"],
            ["name" => "Burundi", "slug" => "burundi", "calling_code" => "257", "iso_code_two_digit" => "BI", "iso_code_three_digit" => "BDI"],
            ["name" => "Cambodia", "slug" => "cambodia", "calling_code" => "855", "iso_code_two_digit" => "KH", "iso_code_three_digit" => "KHM"],
            ["name" => "Cameroon", "slug" => "cameroon", "calling_code" => "237", "iso_code_two_digit" => "CM", "iso_code_three_digit" => "CMR"],
            ["name" => "Canada", "slug" => "canada", "calling_code" => "1", "iso_code_two_digit" => "CA", "iso_code_three_digit" => "CAN"],
            ["name" => "Cape Verde", "slug" => "cape-verde", "calling_code" => "238", "iso_code_two_digit" => "CV", "iso_code_three_digit" => "CPV"],
            ["name" => "Cayman Islands", "slug" => "cayman-islands", "calling_code" => "1345", "iso_code_two_digit" => "KY", "iso_code_three_digit" => "CYM"],
            ["name" => "Central African Republic", "slug" => "central-african-republic", "calling_code" => "236", "iso_code_two_digit" => "CF", "iso_code_three_digit" => "CAF"],
            ["name" => "Chad", "slug" => "chad", "calling_code" => "235", "iso_code_two_digit" => "TD", "iso_code_three_digit" => "TCD"],
            ["name" => "Chile", "slug" => "chile", "calling_code" => "56", "iso_code_two_digit" => "CL", "iso_code_three_digit" => "CHL"],
            ["name" => "China", "slug" => "china", "calling_code" => "86", "iso_code_two_digit" => "CN", "iso_code_three_digit" => "CHN"],
            ["name" => "Christmas Island", "slug" => "christmas-island", "calling_code" => "61", "iso_code_two_digit" => "CX", "iso_code_three_digit" => "CXR"],
            ["name" => "Cocos (Keeling) Islands", "slug" => "cocos-(keeling)-islands", "calling_code" => "672", "iso_code_two_digit" => "CC", "iso_code_three_digit" => "CCK"],
            ["name" => "Colombia", "slug" => "colombia", "calling_code" => "57", "iso_code_two_digit" => "CO", "iso_code_three_digit" => "COL"],
            ["name" => "Comoros", "slug" => "comoros", "calling_code" => "269", "iso_code_two_digit" => "KM", "iso_code_three_digit" => "COM"],
            ["name" => "Congo", "slug" => "congo", "calling_code" => "242", "iso_code_two_digit" => "CG", "iso_code_three_digit" => "COG"],
            ["name" => "Congo, Democratic Republic of the Congo", "slug" => "congo-democratic-republic-of-the-congo", "calling_code" => "242", "iso_code_two_digit" => "CD", "iso_code_three_digit" => "COD"],
            ["name" => "Cook Islands", "slug" => "cook-islands", "calling_code" => "682", "iso_code_two_digit" => "CK", "iso_code_three_digit" => "COK"],
            ["name" => "Costa Rica", "slug" => "costa-rica", "calling_code" => "506", "iso_code_two_digit" => "CR", "iso_code_three_digit" => "CRI"],
            ["name" => "Cote D'Ivoire", "slug" => "cote-d'ivoire", "calling_code" => "225", "iso_code_two_digit" => "CI", "iso_code_three_digit" => "CIV"],
            ["name" => "Croatia", "slug" => "croatia", "calling_code" => "385", "iso_code_two_digit" => "HR", "iso_code_three_digit" => "HRV"],
            ["name" => "Cuba", "slug" => "cuba", "calling_code" => "53", "iso_code_two_digit" => "CU", "iso_code_three_digit" => "CUB"],
            ["name" => "Curacao", "slug" => "curacao", "calling_code" => "599", "iso_code_two_digit" => "CW", "iso_code_three_digit" => "CUW"],
            ["name" => "Cyprus", "slug" => "cyprus", "calling_code" => "357", "iso_code_two_digit" => "CY", "iso_code_three_digit" => "CYP"],
            ["name" => "Czech Republic", "slug" => "czech-republic", "calling_code" => "420", "iso_code_two_digit" => "CZ", "iso_code_three_digit" => "CZE"],
            ["name" => "Denmark", "slug" => "denmark", "calling_code" => "45", "iso_code_two_digit" => "DK", "iso_code_three_digit" => "DNK"],
            ["name" => "Djibouti", "slug" => "djibouti", "calling_code" => "253", "iso_code_two_digit" => "DJ", "iso_code_three_digit" => "DJI"],
            ["name" => "Dominica", "slug" => "dominica", "calling_code" => "1767", "iso_code_two_digit" => "DM", "iso_code_three_digit" => "DMA"],
            ["name" => "Dominican Republic", "slug" => "dominican-republic", "calling_code" => "1809", "iso_code_two_digit" => "DO", "iso_code_three_digit" => "DOM"],
            ["name" => "Ecuador", "slug" => "ecuador", "calling_code" => "593", "iso_code_two_digit" => "EC", "iso_code_three_digit" => "ECU"],
            ["name" => "Egypt", "slug" => "egypt", "calling_code" => "20", "iso_code_two_digit" => "EG", "iso_code_three_digit" => "EGY"],
            ["name" => "El Salvador", "slug" => "el-salvador", "calling_code" => "503", "iso_code_two_digit" => "SV", "iso_code_three_digit" => "SLV"],
            ["name" => "Equatorial Guinea", "slug" => "equatorial-guinea", "calling_code" => "240", "iso_code_two_digit" => "GQ", "iso_code_three_digit" => "GNQ"],
            ["name" => "Eritrea", "slug" => "eritrea", "calling_code" => "291", "iso_code_two_digit" => "ER", "iso_code_three_digit" => "ERI"],
            ["name" => "Estonia", "slug" => "estonia", "calling_code" => "372", "iso_code_two_digit" => "EE", "iso_code_three_digit" => "EST"],
            ["name" => "Ethiopia", "slug" => "ethiopia", "calling_code" => "251", "iso_code_two_digit" => "ET", "iso_code_three_digit" => "ETH"],
            ["name" => "Falkland Islands (Malvinas)", "slug" => "falkland-islands-(malvinas)", "calling_code" => "500", "iso_code_two_digit" => "FK", "iso_code_three_digit" => "FLK"],
            ["name" => "Faroe Islands", "slug" => "faroe-islands", "calling_code" => "298", "iso_code_two_digit" => "FO", "iso_code_three_digit" => "FRO"],
            ["name" => "Fiji", "slug" => "fiji", "calling_code" => "679", "iso_code_two_digit" => "FJ", "iso_code_three_digit" => "FJI"],
            ["name" => "Finland", "slug" => "finland", "calling_code" => "358", "iso_code_two_digit" => "FI", "iso_code_three_digit" => "FIN"],
            ["name" => "France", "slug" => "france", "calling_code" => "33", "iso_code_two_digit" => "FR", "iso_code_three_digit" => "FRA"],
            ["name" => "French Guiana", "slug" => "french-guiana", "calling_code" => "594", "iso_code_two_digit" => "GF", "iso_code_three_digit" => "GUF"],
            ["name" => "French Polynesia", "slug" => "french-polynesia", "calling_code" => "689", "iso_code_two_digit" => "PF", "iso_code_three_digit" => "PYF"],
            ["name" => "French Southern Territories", "slug" => "french-southern-territories", "calling_code" => "262", "iso_code_two_digit" => "TF", "iso_code_three_digit" => "ATF"],
            ["name" => "Gabon", "slug" => "gabon", "calling_code" => "241", "iso_code_two_digit" => "GA", "iso_code_three_digit" => "GAB"],
            ["name" => "Gambia", "slug" => "gambia", "calling_code" => "220", "iso_code_two_digit" => "GM", "iso_code_three_digit" => "GMB"],
            ["name" => "Georgia", "slug" => "georgia", "calling_code" => "995", "iso_code_two_digit" => "GE", "iso_code_three_digit" => "GEO"],
            ["name" => "Germany", "slug" => "germany", "calling_code" => "49", "iso_code_two_digit" => "DE", "iso_code_three_digit" => "DEU"],
            ["name" => "Ghana", "slug" => "ghana", "calling_code" => "233", "iso_code_two_digit" => "GH", "iso_code_three_digit" => "GHA"],
            ["name" => "Gibraltar", "slug" => "gibraltar", "calling_code" => "350", "iso_code_two_digit" => "GI", "iso_code_three_digit" => "GIB"],
            ["name" => "Greece", "slug" => "greece", "calling_code" => "30", "iso_code_two_digit" => "GR", "iso_code_three_digit" => "GRC"],
            ["name" => "Greenland", "slug" => "greenland", "calling_code" => "299", "iso_code_two_digit" => "GL", "iso_code_three_digit" => "GRL"],
            ["name" => "Grenada", "slug" => "grenada", "calling_code" => "1473", "iso_code_two_digit" => "GD", "iso_code_three_digit" => "GRD"],
            ["name" => "Guadeloupe", "slug" => "guadeloupe", "calling_code" => "590", "iso_code_two_digit" => "GP", "iso_code_three_digit" => "GLP"],
            ["name" => "Guam", "slug" => "guam", "calling_code" => "1671", "iso_code_two_digit" => "GU", "iso_code_three_digit" => "GUM"],
            ["name" => "Guatemala", "slug" => "guatemala", "calling_code" => "502", "iso_code_two_digit" => "GT", "iso_code_three_digit" => "GTM"],
            ["name" => "Guernsey", "slug" => "guernsey", "calling_code" => "44", "iso_code_two_digit" => "GG", "iso_code_three_digit" => "GGY"],
            ["name" => "Guinea", "slug" => "guinea", "calling_code" => "224", "iso_code_two_digit" => "GN", "iso_code_three_digit" => "GIN"],
            ["name" => "Guinea-Bissau", "slug" => "guinea-bissau", "calling_code" => "245", "iso_code_two_digit" => "GW", "iso_code_three_digit" => "GNB"],
            ["name" => "Guyana", "slug" => "guyana", "calling_code" => "592", "iso_code_two_digit" => "GY", "iso_code_three_digit" => "GUY"],
            ["name" => "Haiti", "slug" => "haiti", "calling_code" => "509", "iso_code_two_digit" => "HT", "iso_code_three_digit" => "HTI"],
            ["name" => "Heard Island and Mcdonald Islands", "slug" => "heard-island-and-mcdonald-islands", "calling_code" => "0", "iso_code_two_digit" => "HM", "iso_code_three_digit" => "HMD"],
            ["name" => "Holy See (Vatican City State)", "slug" => "holy-see-(vatican-city-state)", "calling_code" => "39", "iso_code_two_digit" => "VA", "iso_code_three_digit" => "VAT"],
            ["name" => "Honduras", "slug" => "honduras", "calling_code" => "504", "iso_code_two_digit" => "HN", "iso_code_three_digit" => "HND"],
            ["name" => "Hong Kong", "slug" => "hong-kong", "calling_code" => "852", "iso_code_two_digit" => "HK", "iso_code_three_digit" => "HKG"],
            ["name" => "Hungary", "slug" => "hungary", "calling_code" => "36", "iso_code_two_digit" => "HU", "iso_code_three_digit" => "HUN"],
            ["name" => "Iceland", "slug" => "iceland", "calling_code" => "354", "iso_code_two_digit" => "IS", "iso_code_three_digit" => "ISL"],
            ["name" => "India", "slug" => "india", "calling_code" => "91", "iso_code_two_digit" => "IN", "iso_code_three_digit" => "IND"],
            ["name" => "Indonesia", "slug" => "indonesia", "calling_code" => "62", "iso_code_two_digit" => "ID", "iso_code_three_digit" => "IDN"],
            ["name" => "Iran, Islamic Republic of", "slug" => "iran-islamic-republic-of", "calling_code" => "98", "iso_code_two_digit" => "IR", "iso_code_three_digit" => "IRN"],
            ["name" => "Iraq", "slug" => "iraq", "calling_code" => "964", "iso_code_two_digit" => "IQ", "iso_code_three_digit" => "IRQ"],
            ["name" => "Ireland", "slug" => "ireland", "calling_code" => "353", "iso_code_two_digit" => "IE", "iso_code_three_digit" => "IRL"],
            ["name" => "Isle of Man", "slug" => "isle-of-man", "calling_code" => "44", "iso_code_two_digit" => "IM", "iso_code_three_digit" => "IMN"],
            ["name" => "Israel", "slug" => "israel", "calling_code" => "972", "iso_code_two_digit" => "IL", "iso_code_three_digit" => "ISR"],
            ["name" => "Italy", "slug" => "italy", "calling_code" => "39", "iso_code_two_digit" => "IT", "iso_code_three_digit" => "ITA"],
            ["name" => "Jamaica", "slug" => "jamaica", "calling_code" => "1876", "iso_code_two_digit" => "JM", "iso_code_three_digit" => "JAM"],
            ["name" => "Japan", "slug" => "japan", "calling_code" => "81", "iso_code_two_digit" => "JP", "iso_code_three_digit" => "JPN"],
            ["name" => "Jersey", "slug" => "jersey", "calling_code" => "44", "iso_code_two_digit" => "JE", "iso_code_three_digit" => "JEY"],
            ["name" => "Jordan", "slug" => "jordan", "calling_code" => "962", "iso_code_two_digit" => "JO", "iso_code_three_digit" => "JOR"],
            ["name" => "Kazakhstan", "slug" => "kazakhstan", "calling_code" => "7", "iso_code_two_digit" => "KZ", "iso_code_three_digit" => "KAZ"],
            ["name" => "Kenya", "slug" => "kenya", "calling_code" => "254", "iso_code_two_digit" => "KE", "iso_code_three_digit" => "KEN"],
            ["name" => "Kiribati", "slug" => "kiribati", "calling_code" => "686", "iso_code_two_digit" => "KI", "iso_code_three_digit" => "KIR"],
            ["name" => "Korea, Democratic People's Republic of", "slug" => "korea-democratic-people's-republic-of", "calling_code" => "850", "iso_code_two_digit" => "KP", "iso_code_three_digit" => "PRK"],
            ["name" => "Korea, Republic of", "slug" => "korea-republic-of", "calling_code" => "82", "iso_code_two_digit" => "KR", "iso_code_three_digit" => "KOR"],
            ["name" => "Kosovo", "slug" => "kosovo", "calling_code" => "381", "iso_code_two_digit" => "XK", "iso_code_three_digit" => "XKX"],
            ["name" => "Kuwait", "slug" => "kuwait", "calling_code" => "965", "iso_code_two_digit" => "KW", "iso_code_three_digit" => "KWT"],
            ["name" => "Kyrgyzstan", "slug" => "kyrgyzstan", "calling_code" => "996", "iso_code_two_digit" => "KG", "iso_code_three_digit" => "KGZ"],
            ["name" => "Lao People's Democratic Republic", "slug" => "lao-people's-democratic-republic", "calling_code" => "856", "iso_code_two_digit" => "LA", "iso_code_three_digit" => "LAO"],
            ["name" => "Latvia", "slug" => "latvia", "calling_code" => "371", "iso_code_two_digit" => "LV", "iso_code_three_digit" => "LVA"],
            ["name" => "Lebanon", "slug" => "lebanon", "calling_code" => "961", "iso_code_two_digit" => "LB", "iso_code_three_digit" => "LBN"],
            ["name" => "Lesotho", "slug" => "lesotho", "calling_code" => "266", "iso_code_two_digit" => "LS", "iso_code_three_digit" => "LSO"],
            ["name" => "Liberia", "slug" => "liberia", "calling_code" => "231", "iso_code_two_digit" => "LR", "iso_code_three_digit" => "LBR"],
            ["name" => "Libyan Arab Jamahiriya", "slug" => "libyan-arab-jamahiriya", "calling_code" => "218", "iso_code_two_digit" => "LY", "iso_code_three_digit" => "LBY"],
            ["name" => "Liechtenstein", "slug" => "liechtenstein", "calling_code" => "423", "iso_code_two_digit" => "LI", "iso_code_three_digit" => "LIE"],
            ["name" => "Lithuania", "slug" => "lithuania", "calling_code" => "370", "iso_code_two_digit" => "LT", "iso_code_three_digit" => "LTU"],
            ["name" => "Luxembourg", "slug" => "luxembourg", "calling_code" => "352", "iso_code_two_digit" => "LU", "iso_code_three_digit" => "LUX"],
            ["name" => "Macao", "slug" => "macao", "calling_code" => "853", "iso_code_two_digit" => "MO", "iso_code_three_digit" => "MAC"],
            ["name" => "Macedonia, the Former Yugoslav Republic of", "slug" => "macedonia-the-former-yugoslav-republic-of", "calling_code" => "389", "iso_code_two_digit" => "MK", "iso_code_three_digit" => "MKD"],
            ["name" => "Madagascar", "slug" => "madagascar", "calling_code" => "261", "iso_code_two_digit" => "MG", "iso_code_three_digit" => "MDG"],
            ["name" => "Malawi", "slug" => "malawi", "calling_code" => "265", "iso_code_two_digit" => "MW", "iso_code_three_digit" => "MWI"],
            ["name" => "Malaysia", "slug" => "malaysia", "calling_code" => "60", "iso_code_two_digit" => "MY", "iso_code_three_digit" => "MYS"],
            ["name" => "Maldives", "slug" => "maldives", "calling_code" => "960", "iso_code_two_digit" => "MV", "iso_code_three_digit" => "MDV"],
            ["name" => "Mali", "slug" => "mali", "calling_code" => "223", "iso_code_two_digit" => "ML", "iso_code_three_digit" => "MLI"],
            ["name" => "Malta", "slug" => "malta", "calling_code" => "356", "iso_code_two_digit" => "MT", "iso_code_three_digit" => "MLT"],
            ["name" => "Marshall Islands", "slug" => "marshall-islands", "calling_code" => "692", "iso_code_two_digit" => "MH", "iso_code_three_digit" => "MHL"],
            ["name" => "Martinique", "slug" => "martinique", "calling_code" => "596", "iso_code_two_digit" => "MQ", "iso_code_three_digit" => "MTQ"],
            ["name" => "Mauritania", "slug" => "mauritania", "calling_code" => "222", "iso_code_two_digit" => "MR", "iso_code_three_digit" => "MRT"],
            ["name" => "Mauritius", "slug" => "mauritius", "calling_code" => "230", "iso_code_two_digit" => "MU", "iso_code_three_digit" => "MUS"],
            ["name" => "Mayotte", "slug" => "mayotte", "calling_code" => "269", "iso_code_two_digit" => "YT", "iso_code_three_digit" => "MYT"],
            ["name" => "Mexico", "slug" => "mexico", "calling_code" => "52", "iso_code_two_digit" => "MX", "iso_code_three_digit" => "MEX"],
            ["name" => "Micronesia, Federated States of", "slug" => "micronesia-federated-states-of", "calling_code" => "691", "iso_code_two_digit" => "FM", "iso_code_three_digit" => "FSM"],
            ["name" => "Moldova, Republic of", "slug" => "moldova-republic-of", "calling_code" => "373", "iso_code_two_digit" => "MD", "iso_code_three_digit" => "MDA"],
            ["name" => "Monaco", "slug" => "monaco", "calling_code" => "377", "iso_code_two_digit" => "MC", "iso_code_three_digit" => "MCO"],
            ["name" => "Mongolia", "slug" => "mongolia", "calling_code" => "976", "iso_code_two_digit" => "MN", "iso_code_three_digit" => "MNG"],
            ["name" => "Montenegro", "slug" => "montenegro", "calling_code" => "382", "iso_code_two_digit" => "ME", "iso_code_three_digit" => "MNE"],
            ["name" => "Montserrat", "slug" => "montserrat", "calling_code" => "1664", "iso_code_two_digit" => "MS", "iso_code_three_digit" => "MSR"],
            ["name" => "Morocco", "slug" => "morocco", "calling_code" => "212", "iso_code_two_digit" => "MA", "iso_code_three_digit" => "MAR"],
            ["name" => "Mozambique", "slug" => "mozambique", "calling_code" => "258", "iso_code_two_digit" => "MZ", "iso_code_three_digit" => "MOZ"],
            ["name" => "Myanmar", "slug" => "myanmar", "calling_code" => "95", "iso_code_two_digit" => "MM", "iso_code_three_digit" => "MMR"],
            ["name" => "Namibia", "slug" => "namibia", "calling_code" => "264", "iso_code_two_digit" => "NA", "iso_code_three_digit" => "NAM"],
            ["name" => "Nauru", "slug" => "nauru", "calling_code" => "674", "iso_code_two_digit" => "NR", "iso_code_three_digit" => "NRU"],
            ["name" => "Nepal", "slug" => "nepal", "calling_code" => "977", "iso_code_two_digit" => "NP", "iso_code_three_digit" => "NPL"],
            ["name" => "Netherlands", "slug" => "netherlands", "calling_code" => "31", "iso_code_two_digit" => "NL", "iso_code_three_digit" => "NLD"],
            ["name" => "Netherlands Antilles", "slug" => "netherlands-antilles", "calling_code" => "599", "iso_code_two_digit" => "AN", "iso_code_three_digit" => "ANT"],
            ["name" => "New Caledonia", "slug" => "new-caledonia", "calling_code" => "687", "iso_code_two_digit" => "NC", "iso_code_three_digit" => "NCL"],
            ["name" => "New Zealand", "slug" => "new-zealand", "calling_code" => "64", "iso_code_two_digit" => "NZ", "iso_code_three_digit" => "NZL"],
            ["name" => "Nicaragua", "slug" => "nicaragua", "calling_code" => "505", "iso_code_two_digit" => "NI", "iso_code_three_digit" => "NIC"],
            ["name" => "Niger", "slug" => "niger", "calling_code" => "227", "iso_code_two_digit" => "NE", "iso_code_three_digit" => "NER"],
            ["name" => "Nigeria", "slug" => "nigeria", "calling_code" => "234", "iso_code_two_digit" => "NG", "iso_code_three_digit" => "NGA"],
            ["name" => "Niue", "slug" => "niue", "calling_code" => "683", "iso_code_two_digit" => "NU", "iso_code_three_digit" => "NIU"],
            ["name" => "Norfolk Island", "slug" => "norfolk-island", "calling_code" => "672", "iso_code_two_digit" => "NF", "iso_code_three_digit" => "NFK"],
            ["name" => "Northern Mariana Islands", "slug" => "northern-mariana-islands", "calling_code" => "1670", "iso_code_two_digit" => "MP", "iso_code_three_digit" => "MNP"],
            ["name" => "Norway", "slug" => "norway", "calling_code" => "47", "iso_code_two_digit" => "NO", "iso_code_three_digit" => "NOR"],
            ["name" => "Oman", "slug" => "oman", "calling_code" => "968", "iso_code_two_digit" => "OM", "iso_code_three_digit" => "OMN"],
            ["name" => "Pakistan", "slug" => "pakistan", "calling_code" => "92", "iso_code_two_digit" => "PK", "iso_code_three_digit" => "PAK"],
            ["name" => "Palau", "slug" => "palau", "calling_code" => "680", "iso_code_two_digit" => "PW", "iso_code_three_digit" => "PLW"],
            ["name" => "Palestinian Territory, Occupied", "slug" => "palestinian-territory-occupied", "calling_code" => "970", "iso_code_two_digit" => "PS", "iso_code_three_digit" => "PSE"],
            ["name" => "Panama", "slug" => "panama", "calling_code" => "507", "iso_code_two_digit" => "PA", "iso_code_three_digit" => "PAN"],
            ["name" => "Papua New Guinea", "slug" => "papua-new-guinea", "calling_code" => "675", "iso_code_two_digit" => "PG", "iso_code_three_digit" => "PNG"],
            ["name" => "Paraguay", "slug" => "paraguay", "calling_code" => "595", "iso_code_two_digit" => "PY", "iso_code_three_digit" => "PRY"],
            ["name" => "Peru", "slug" => "peru", "calling_code" => "51", "iso_code_two_digit" => "PE", "iso_code_three_digit" => "PER"],
            ["name" => "Philippines", "slug" => "philippines", "calling_code" => "63", "iso_code_two_digit" => "PH", "iso_code_three_digit" => "PHL"],
            ["name" => "Pitcairn", "slug" => "pitcairn", "calling_code" => "64", "iso_code_two_digit" => "PN", "iso_code_three_digit" => "PCN"],
            ["name" => "Poland", "slug" => "poland", "calling_code" => "48", "iso_code_two_digit" => "PL", "iso_code_three_digit" => "POL"],
            ["name" => "Portugal", "slug" => "portugal", "calling_code" => "351", "iso_code_two_digit" => "PT", "iso_code_three_digit" => "PRT"],
            ["name" => "Puerto Rico", "slug" => "puerto-rico", "calling_code" => "1787", "iso_code_two_digit" => "PR", "iso_code_three_digit" => "PRI"],
            ["name" => "Qatar", "slug" => "qatar", "calling_code" => "974", "iso_code_two_digit" => "QA", "iso_code_three_digit" => "QAT"],
            ["name" => "Reunion", "slug" => "reunion", "calling_code" => "262", "iso_code_two_digit" => "RE", "iso_code_three_digit" => "REU"],
            ["name" => "Romania", "slug" => "romania", "calling_code" => "40", "iso_code_two_digit" => "RO", "iso_code_three_digit" => "ROM"],
            ["name" => "Russian Federation", "slug" => "russian-federation", "calling_code" => "70", "iso_code_two_digit" => "RU", "iso_code_three_digit" => "RUS"],
            ["name" => "Rwanda", "slug" => "rwanda", "calling_code" => "250", "iso_code_two_digit" => "RW", "iso_code_three_digit" => "RWA"],
            ["name" => "Saint Barthelemy", "slug" => "saint-barthelemy", "calling_code" => "590", "iso_code_two_digit" => "BL", "iso_code_three_digit" => "BLM"],
            ["name" => "Saint Helena", "slug" => "saint-helena", "calling_code" => "290", "iso_code_two_digit" => "SH", "iso_code_three_digit" => "SHN"],
            ["name" => "Saint Kitts and Nevis", "slug" => "saint-kitts-and-nevis", "calling_code" => "1869", "iso_code_two_digit" => "KN", "iso_code_three_digit" => "KNA"],
            ["name" => "Saint Lucia", "slug" => "saint-lucia", "calling_code" => "1758", "iso_code_two_digit" => "LC", "iso_code_three_digit" => "LCA"],
            ["name" => "Saint Martin", "slug" => "saint-martin", "calling_code" => "590", "iso_code_two_digit" => "MF", "iso_code_three_digit" => "MAF"],
            ["name" => "Saint Pierre and Miquelon", "slug" => "saint-pierre-and-miquelon", "calling_code" => "508", "iso_code_two_digit" => "PM", "iso_code_three_digit" => "SPM"],
            ["name" => "Saint Vincent and the Grenadines", "slug" => "saint-vincent-and-the-grenadines", "calling_code" => "1784", "iso_code_two_digit" => "VC", "iso_code_three_digit" => "VCT"],
            ["name" => "Samoa", "slug" => "samoa", "calling_code" => "684", "iso_code_two_digit" => "WS", "iso_code_three_digit" => "WSM"],
            ["name" => "San Marino", "slug" => "san-marino", "calling_code" => "378", "iso_code_two_digit" => "SM", "iso_code_three_digit" => "SMR"],
            ["name" => "Sao Tome and Principe", "slug" => "sao-tome-and-principe", "calling_code" => "239", "iso_code_two_digit" => "ST", "iso_code_three_digit" => "STP"],
            ["name" => "Saudi Arabia", "slug" => "saudi-arabia", "calling_code" => "966", "iso_code_two_digit" => "SA", "iso_code_three_digit" => "SAU"],
            ["name" => "Senegal", "slug" => "senegal", "calling_code" => "221", "iso_code_two_digit" => "SN", "iso_code_three_digit" => "SEN"],
            ["name" => "Serbia", "slug" => "serbia", "calling_code" => "381", "iso_code_two_digit" => "RS", "iso_code_three_digit" => "SRB"],
            ["name" => "Serbia and Montenegro", "slug" => "serbia-and-montenegro", "calling_code" => "381", "iso_code_two_digit" => "CS", "iso_code_three_digit" => "SCG"],
            ["name" => "Seychelles", "slug" => "seychelles", "calling_code" => "248", "iso_code_two_digit" => "SC", "iso_code_three_digit" => "SYC"],
            ["name" => "Sierra Leone", "slug" => "sierra-leone", "calling_code" => "232", "iso_code_two_digit" => "SL", "iso_code_three_digit" => "SLE"],
            ["name" => "Singapore", "slug" => "singapore", "calling_code" => "65", "iso_code_two_digit" => "SG", "iso_code_three_digit" => "SGP"],
            ["name" => "Sint Maarten", "slug" => "sint-maarten", "calling_code" => "1", "iso_code_two_digit" => "SX", "iso_code_three_digit" => "SXM"],
            ["name" => "Slovakia", "slug" => "slovakia", "calling_code" => "421", "iso_code_two_digit" => "SK", "iso_code_three_digit" => "SVK"],
            ["name" => "Slovenia", "slug" => "slovenia", "calling_code" => "386", "iso_code_two_digit" => "SI", "iso_code_three_digit" => "SVN"],
            ["name" => "Solomon Islands", "slug" => "solomon-islands", "calling_code" => "677", "iso_code_two_digit" => "SB", "iso_code_three_digit" => "SLB"],
            ["name" => "Somalia", "slug" => "somalia", "calling_code" => "252", "iso_code_two_digit" => "SO", "iso_code_three_digit" => "SOM"],
            ["name" => "South Africa", "slug" => "south-africa", "calling_code" => "27", "iso_code_two_digit" => "ZA", "iso_code_three_digit" => "ZAF"],
            ["name" => "South Georgia and the South Sandwich Islands", "slug" => "south-georgia-and-the-south-sandwich-islands", "calling_code" => "500", "iso_code_two_digit" => "GS", "iso_code_three_digit" => "SGS"],
            ["name" => "South Sudan", "slug" => "south-sudan", "calling_code" => "211", "iso_code_two_digit" => "SS", "iso_code_three_digit" => "SSD"],
            ["name" => "Spain", "slug" => "spain", "calling_code" => "34", "iso_code_two_digit" => "ES", "iso_code_three_digit" => "ESP"],
            ["name" => "Sri Lanka", "slug" => "sri-lanka", "calling_code" => "94", "iso_code_two_digit" => "LK", "iso_code_three_digit" => "LKA"],
            ["name" => "Sudan", "slug" => "sudan", "calling_code" => "249", "iso_code_two_digit" => "SD", "iso_code_three_digit" => "SDN"],
            ["name" => "Suriname", "slug" => "suriname", "calling_code" => "597", "iso_code_two_digit" => "SR", "iso_code_three_digit" => "SUR"],
            ["name" => "Svalbard and Jan Mayen", "slug" => "svalbard-and-jan-mayen", "calling_code" => "47", "iso_code_two_digit" => "SJ", "iso_code_three_digit" => "SJM"],
            ["name" => "Swaziland", "slug" => "swaziland", "calling_code" => "268", "iso_code_two_digit" => "SZ", "iso_code_three_digit" => "SWZ"],
            ["name" => "Sweden", "slug" => "sweden", "calling_code" => "46", "iso_code_two_digit" => "SE", "iso_code_three_digit" => "SWE"],
            ["name" => "Switzerland", "slug" => "switzerland", "calling_code" => "41", "iso_code_two_digit" => "CH", "iso_code_three_digit" => "CHE"],
            ["name" => "Syrian Arab Republic", "slug" => "syrian-arab-republic", "calling_code" => "963", "iso_code_two_digit" => "SY", "iso_code_three_digit" => "SYR"],
            ["name" => "Taiwan, Province of China", "slug" => "taiwan-province-of-china", "calling_code" => "886", "iso_code_two_digit" => "TW", "iso_code_three_digit" => "TWN"],
            ["name" => "Tajikistan", "slug" => "tajikistan", "calling_code" => "992", "iso_code_two_digit" => "TJ", "iso_code_three_digit" => "TJK"],
            ["name" => "Tanzania, United Republic of", "slug" => "tanzania-united-republic-of", "calling_code" => "255", "iso_code_two_digit" => "TZ", "iso_code_three_digit" => "TZA"],
            ["name" => "Thailand", "slug" => "thailand", "calling_code" => "66", "iso_code_two_digit" => "TH", "iso_code_three_digit" => "THA"],
            ["name" => "Timor-Leste", "slug" => "timor-leste", "calling_code" => "670", "iso_code_two_digit" => "TL", "iso_code_three_digit" => "TLS"],
            ["name" => "Togo", "slug" => "togo", "calling_code" => "228", "iso_code_two_digit" => "TG", "iso_code_three_digit" => "TGO"],
            ["name" => "Tokelau", "slug" => "tokelau", "calling_code" => "690", "iso_code_two_digit" => "TK", "iso_code_three_digit" => "TKL"],
            ["name" => "Tonga", "slug" => "tonga", "calling_code" => "676", "iso_code_two_digit" => "TO", "iso_code_three_digit" => "TON"],
            ["name" => "Trinidad and Tobago", "slug" => "trinidad-and-tobago", "calling_code" => "1868", "iso_code_two_digit" => "TT", "iso_code_three_digit" => "TTO"],
            ["name" => "Tunisia", "slug" => "tunisia", "calling_code" => "216", "iso_code_two_digit" => "TN", "iso_code_three_digit" => "TUN"],
            ["name" => "Turkey", "slug" => "turkey", "calling_code" => "90", "iso_code_two_digit" => "TR", "iso_code_three_digit" => "TUR"],
            ["name" => "Turkmenistan", "slug" => "turkmenistan", "calling_code" => "7370", "iso_code_two_digit" => "TM", "iso_code_three_digit" => "TKM"],
            ["name" => "Turks and Caicos Islands", "slug" => "turks-and-caicos-islands", "calling_code" => "1649", "iso_code_two_digit" => "TC", "iso_code_three_digit" => "TCA"],
            ["name" => "Tuvalu", "slug" => "tuvalu", "calling_code" => "688", "iso_code_two_digit" => "TV", "iso_code_three_digit" => "TUV"],
            ["name" => "Uganda", "slug" => "uganda", "calling_code" => "256", "iso_code_two_digit" => "UG", "iso_code_three_digit" => "UGA"],
            ["name" => "Ukraine", "slug" => "ukraine", "calling_code" => "380", "iso_code_two_digit" => "UA", "iso_code_three_digit" => "UKR"],
            ["name" => "United Arab Emirates", "slug" => "united-arab-emirates", "calling_code" => "971", "iso_code_two_digit" => "AE", "iso_code_three_digit" => "ARE"],
            ["name" => "United Kingdom", "slug" => "united-kingdom", "calling_code" => "44", "iso_code_two_digit" => "GB", "iso_code_three_digit" => "GBR"],
            ["name" => "United States", "slug" => "united-states", "calling_code" => "1", "iso_code_two_digit" => "US", "iso_code_three_digit" => "USA"],
            ["name" => "United States Minor Outlying Islands", "slug" => "united-states-minor-outlying-islands", "calling_code" => "1", "iso_code_two_digit" => "UM", "iso_code_three_digit" => "UMI"],
            ["name" => "Uruguay", "slug" => "uruguay", "calling_code" => "598", "iso_code_two_digit" => "UY", "iso_code_three_digit" => "URY"],
            ["name" => "Uzbekistan", "slug" => "uzbekistan", "calling_code" => "998", "iso_code_two_digit" => "UZ", "iso_code_three_digit" => "UZB"],
            ["name" => "Vanuatu", "slug" => "vanuatu", "calling_code" => "678", "iso_code_two_digit" => "VU", "iso_code_three_digit" => "VUT"],
            ["name" => "Venezuela", "slug" => "venezuela", "calling_code" => "58", "iso_code_two_digit" => "VE", "iso_code_three_digit" => "VEN"],
            ["name" => "Viet Nam", "slug" => "viet-nam", "calling_code" => "84", "iso_code_two_digit" => "VN", "iso_code_three_digit" => "VNM"],
            ["name" => "Virgin Islands, British", "slug" => "virgin-islands-british", "calling_code" => "1284", "iso_code_two_digit" => "VG", "iso_code_three_digit" => "VGB"],
            ["name" => "Virgin Islands, U.s.", "slug" => "virgin-islands-us", "calling_code" => "1340", "iso_code_two_digit" => "VI", "iso_code_three_digit" => "VIR"],
            ["name" => "Wallis and Futuna", "slug" => "wallis-and-futuna", "calling_code" => "681", "iso_code_two_digit" => "WF", "iso_code_three_digit" => "WLF"],
            ["name" => "Western Sahara", "slug" => "western-sahara", "calling_code" => "212", "iso_code_two_digit" => "EH", "iso_code_three_digit" => "ESH"],
            ["name" => "Yemen", "slug" => "yemen", "calling_code" => "967", "iso_code_two_digit" => "YE", "iso_code_three_digit" => "YEM"],
            ["name" => "Zambia", "slug" => "zambia", "calling_code" => "260", "iso_code_two_digit" => "ZM", "iso_code_three_digit" => "ZMB"],
            ["name" => "Zimbabwe", "slug" => "zimbabwe", "calling_code" => "263", "iso_code_two_digit" => "ZW", "iso_code_three_digit" => "ZWE"],
        ]);
    }
}
